# .github/workflows/ci.yml
name: CI Pipeline para Python

on:
  push:
    branches:
      - vizcaino 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con pytest
        run: pytest

      - name: Debug - Listar archivos
        run: |
          echo "Directorio actual:"
          pwd
          echo "Archivos encontrados:"
          ls -R

      - name: pruebas de ssh con el servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST  }}
          port: ${{ secrets.VPS_SSH_PORT  }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD  }}
          script: | 
            echo " Conexion exitosa desde GitHub Actions"
            pwd
            date
            whoami
            hostname
            uptime

      - name: pasar el stack.yml al servidor
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST  }}
          port: ${{ secrets.VPS_SSH_PORT  }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD  }}
          source: "stack.yml"
          target: "/home/${{  secrets.VPS_USER  }}/automatizar"